# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Sakura` Blogs
subtitle: ''
description: '或苦或甜都不要辜负'
keywords: '仅安的小站'
author: 仅安
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jinan6.vip     # Github
root: /                     # Github
# permalink: :title/
# permalink_defaults:
permalink: posts/:abbrlink/
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: dec   #support dec(default) and hex
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # 默认的新博文名称
default_layout: post    # 默认布局
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0    #把博客名称改成小写/大写（1,2）
render_drafts: false    # 是否显示草稿
post_asset_folder: true    #是否启用资源文件夹（用来存放相对路径图片或文件）
relative_link: false    # 把链接改为与根目录的相对位址
future: true
highlight:
  enable: true  #是否开启代码高亮
  line_number: true  #是否增加代码行号
  auto_detect: true #自动判断代码语言
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:     #首页博客分布
  path: ''      #博客的默认路径
  per_page: 10  #每页博客数量上限
  order_by: -date   #博客排序

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD #博客日期格式
time_format: HH:mm:ss   #博客时间格式
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:jinan6/jinan6.github.io.git
  branch: master

#备份
backup:
  type: git
  theme: butterfly
  message: Butterfly 3.3.0-b2版本
  repository:
    github: git@github.com:jinan6/jinan6.github.io.git,butterfly

#Rss插件
# plugins: hexo-generate-feed

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: ./live2d_models/models/kesyoban # 血小板
    # use: ./live2d_models/models/tororo # 白猫
    # use: ./live2d_models/models/hijiki # 黑猫
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false   #是否在手机上显示
  react:
    opacity: 1.0  #透明度
#
aplayer:
  meting: false
  asset_inject: false

# #弹窗
# # offline config passed to sw-precache.
# service_worker:
#   maximumFileSizeToCacheInBytes: 5242880
#   staticFileGlobs:
#   - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
#   # - public/**/*.{html,css}
#   stripPrefix: public
#   verbose: false