favicon: /navigation/images/èŒç‰ˆèˆªç©ºèˆªå¤©-æ˜Ÿæ˜Ÿstar.png
banner: /navigation/images/webstack_banner_cn.png

logo:
  expanded: /navigation/images/logo1.png
  collapsed: /navigation/images/logo1.png
  dark: /navigation/images/logo_dark.png

flag:
  icon: flag-cn
  name: Chinese

# githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: å¸¸ç”¨å·¥å…·
    icon: fa fa-folder-open
    submenu:
      - name: åšå®¢ç›¸å…³
        icon: fas fa-battery-empty
        config: correlation
      - name: ç«™é•¿å·¥å…·
        icon: fas fa-battery-quarter
        config: people
      - name: ITå·¥å…·ç®±
        icon: fas fa-battery-half
        config: tool
  

  - name: ç´ æèµ„æº
    icon: fas fa-archive
    submenu:
      - name: å›¾æ ‡ç´ æ
        icon: fas fa-bolt
        config: icon
      - name: å›¾ç‰‡ç´ æ
        icon: fas fa-images
        config: photo
      - name: è®¾è®¡ç›¸å…³
        icon: fas fa-dove
        config: Logo

  - name: å­¦ä¹ æ•™ç¨‹
    icon: fas fa-book
    submenu:
      - name: å­¦ä¹ å¹³å°
        icon: fas fa-laptop-code
        config: study
      - name: å‰ç«¯ç›¸å…³
        icon: fas fa-mouse
        config: qianduan
      - name: å¸¸ç”¨ç±»åº“
        icon: fas fa-paper-plane
        config: class
      - name: å¸¸ç”¨ç½‘å€
        icon: fas fa-carrot
        config: website

  - name: å¼€å‘ç¤¾åŒº
    icon: fas fa-thumbs-up
    submenu:
      - name: ç¤¾åŒºè®ºå›
        icon: fas fa-atom
        config: community
      - name: ä»£ç æ‰˜ç®¡
        icon: fas fa-code
        config: collocation
      - name: äº‘æœåŠ¡å•†
        icon: fas fa-cloud
        config: yun

  - name: ä¸æˆ‘ç›¸å…³
    icon: fas fa-user
    submenu:
      - name: ä¸ªäººç«™ç‚¹
        icon: fas fa-star
        config: me

correlation:
  - name: Hexo
    url: https://hexo.io/zh-cn/
    img: /navigation/images/img/hexo.svg
    description: å¿«é€Ÿã€ç®€æ´ä¸”é«˜æ•ˆçš„åšå®¢æ¡†æ¶
  - name: Vuepress
    url: https://vuepress.vuejs.org/zh/
    img: /navigation/images/img/vuepress.png
    description: Vue é©±åŠ¨çš„é™æ€ç½‘ç«™ç”Ÿæˆå™¨
  - name: Hexo-Butterflyä¸»é¢˜
    url: https://github.com/jerryc127/hexo-theme-butterfly
    img: /navigation/images/img/butterfly.png
    description: ä¸€ä¸ªç®€æ´ã€å¡ç‰‡å¼è®¾è®¡çš„Hexoä¸»é¢˜
  - name: Hexo-volantisä¸»é¢˜
    url: https://volantis.js.org/v3/getting-started/
    img: /navigation/images/img/volantis.png
    description: Volantisï¼Œä¸€ä¸ªé«˜åº¦æ¨¡å—åŒ–å’Œå¯å®šåˆ¶åŒ–ã€åŠŸèƒ½ç›¸å¯¹å®Œå–„çš„ Hexo åšå®¢ä¸»é¢˜
  - name: Valine
    url: https://valine.js.org/
    img: /navigation/images/img/valine.png
    description: ä¸€æ¬¾å¿«é€Ÿã€ç®€æ´ä¸”é«˜æ•ˆçš„æ— åç«¯è¯„è®ºç³»ç»Ÿã€‚
  - name: LeanCloud
    url: https://console.leancloud.app/
    img: /navigation/images/img/leancloud.png
    description: LeanCloud ä¸ºåº”ç”¨å¼€å‘æä¾›ä¸€ç«™å¼è§£å†³æ–¹æ¡ˆ
  - name: Artitalk.js
    url: https://artitalk.js.org/
    img: /navigation/images/img/atico.png
    description: åŸºäº LeanCloud å®ç°çš„å¯å®æ—¶å‘å¸ƒè¯´è¯´/å¾®è¯­çš„ js
  - name: æ˜æœˆæµ©ç©º
    url: https://myhkw.cn/
    img: /navigation/images/img/mingyue.ico
    description: éŸ³ä¹-å½±è§†-Emlog|Z-Blog|WordPress|Typecho|HTML5ç½‘ç«™æ’­æ”¾å™¨
  - name: æ¢¨èŠ±å¸¦é›¨æ’­æ”¾å™¨
    url: https://music.m0x.cn/
    img: /navigation/images/img/lihua.ico
    description: ä¸åªæ˜¯ä¸€æ¬¾äººæ€§åŒ–çš„HTMLç½‘é¡µéŸ³ä¹æ’­æ”¾å™¨æ’ä»¶
  - name: DaoCloud
    url: https://www.daocloud.io/
    img: /navigation/images/img/daocloud.ico
    description: ä¼ä¸šçº§äº‘è®¡ç®—é¢†åŸŸçš„åˆ›æ–°é¢†å¯¼è€…
  - name: UptimeRobot
    url: https://uptimerobot.com/
    img: /navigation/images/img/UptimeRobot.png
    description: å…¨çƒé¢†å…ˆçš„æ­£å¸¸è¿è¡Œæ—¶é—´ç›‘æ§æœåŠ¡
people:
  - name: ç«™é•¿å·¥å…·
    url: http://tool.chinaz.com/
    img: /navigation/images/img/chinaz.png
    description: ç«™é•¿å·¥å…·ï¼ŒSEOå·¥å…·
  - name: é˜¿é‡Œäº‘ whois æŸ¥è¯¢
    url: https://whois.aliyun.com/
    img: /navigation/images/img/aliyun.png
    description: whoisæŸ¥è¯¢,åŸŸåwhois,åŸŸåæ³¨å†Œä¿¡æ¯,whoisæŸ¥è¯¢å·¥å…·,whoisä¿¡æ¯,åŸŸåä¿¡æ¯
  - name: ç™¾åº¦ç«™é•¿å¹³å°
    url: https://ziyuan.baidu.com/
    img: /navigation/images/img/baidu.png
    description: ç™¾åº¦æœç´¢èµ„æºå¹³å° - è®©ç½‘ç«™æ›´å…·ä»·å€¼
  - name: ç™¾åº¦ç»Ÿè®¡
    url: https://tongji.baidu.com/
    img: /navigation/images/img/baidu.png
    description: ç™¾åº¦ç»Ÿè®¡ â€” æœ€å¤§çš„ä¸­æ–‡ç½‘ç«™åˆ†æå¹³å°
tool:
  - name: åœ¨çº¿å·¥å…· - ç¨‹åºå‘˜çš„å·¥å…·ç®±
    url: https://tool.lu/
    img: /navigation/images/img/tool.png
    description: ç«™é•¿å·¥å…·ã€ä»£ç æ ¼å¼åŒ–ã€å‹ç¼©ã€åŠ å¯†ã€è§£å¯†ã€ä¸‹è½½é“¾æ¥è½¬æ¢ç­‰
  - name: åœ¨çº¿å·¥å…· - OSCHINA.NETç¤¾åŒº
    url: https://tool.oschina.net/
    img: /navigation/images/img/tool.png
    description: å¸¸ç”¨æ–‡æ¡£ã€å¸¸ç”¨å¯¹ç…§è¡¨ã€ä»£ç å¤„ç†ã€Html/Js/Csså·¥å…·ã€åŠ å¯†/è½¬ç å·¥å…·ç­‰
  - name: è®°ç£Šå·¥å…·ç®±
    url: https://tools.ly522.com/
    img: /navigation/images/img/tool.png
    description: Dnsæ£€æµ‹ã€CSSæ ¼å¼åŒ–ã€è¶…çº§Pingã€ç«¯å£æ‰«æç­‰
  - name: å­Ÿå¤å·¥å…·ç®±
    url: http://tool.mkblog.cn/
    img: /navigation/images/img/tool.png
    description: cssä¸€é”®ç¾åŒ–ã€æ–‡æœ¬å·®å¼‚æ¯”è¾ƒã€ä»£ç é«˜äº®ç­‰

icon:
  - name: iconfont
    url: https://www.iconfont.cn/
    img: /navigation/images/img/ali.ico
    description: é˜¿é‡Œå·´å·´çŸ¢é‡å›¾æ ‡åº“
  - name: fontawesome
    url: https://fontawesome.com/
    img: /navigation/images/img/fontawesome.png
    description: å®ç”¨çš„å°å›¾æ ‡
  - name: FindIcons
    url: https://findicons.com/
    img: /navigation/images/img/FindIcons.png
    description: Search through 300,000 free icons
  - name: Font Awesome
    url: http://www.fontawesome.com.cn/faicons/
    img: /navigation/images/img/fontawesomeicon.png
    description: è¶…æ¼‚äº®çš„å›¾æ ‡å’Œå­—ä½“åº“
  - name: å°åº·çš„ Font Awesome 5 å›¾æ ‡é€ŸæŸ¥
    url: https://dh.xiaokang.me/font5/
    img: /navigation/images/img/lll.png
    description: ç®€å•å¿«é€Ÿçš„ä½¿ç”¨Font Awesome 5 å›¾æ ‡
  - name: è‡´ç¾åŒ–
    url: https://zhutix.com/
    img: /navigation/images/img/zhimeihua.png
    description: è‡´ç¾åŒ– - æœ€ä¸“ä¸šçš„æ¡Œé¢ç¾åŒ–äº¤æµå¹³å°
photo:
  - name: å¿…åº”å£çº¸
    url: https://bing.ioliu.cn/
    img: /navigation/images/img/bing.png
    description: å¿…åº”æ¯æ—¥é«˜æ¸…å£çº¸
  - name: æç®€å£çº¸
    url: https://bz.zzzmh.cn/
    img: /navigation/images/img/zzzmh.png
    description: é«˜è´¨é‡ç²¾å“å£çº¸
  - name: åƒå›¾ç½‘
    url: https://www.58pic.com/
    img: /navigation/images/img/qiantu.png
    description: ä¸“æ³¨å…è´¹è®¾è®¡ç´ æä¸‹è½½çš„ç½‘ç«™
  - name: wallhaven
    url: https://wallhaven.cc/
    img: /navigation/images/img/wallhaven.ico
    description: é«˜è´¨é‡ç²¾å“å£çº¸
  - name: wallroom
    url: https://wallroom.io/
    img: /navigation/images/img/wallroom.ico
    description: é«˜è´¨é‡ç²¾å“å£çº¸
  - name: wallpaper
    url: https://wall.alphacoders.com/?lang=Chinese
    img: /navigation/images/img/alphacoders.png
    description: é«˜è´¨é‡ç²¾å“å£çº¸
  - name: Simple Desktops
    url: http://simpledesktops.com/
    img: /navigation/images/img/simple.ico
    description: æç®€é£æ ¼çš„å£çº¸
  - name: Pexels
    url: https://www.pexels.com/zh-cn/
    img: /navigation/images/img/pexels.ico
    description: å…è´¹ç´ æå›¾ç‰‡
Logo:
  - name: Fotor
    url: https://www.fotor.com/
    img: /navigation/images/img/fotor.png
    description: ä¸€æ¬¾å¥½ç”¨çš„å›¾ç‰‡è®¾è®¡ç½‘ç«™
  - name: ç‚«é…·é…è‰²
    url: https://www.coocolors.com/
    img: /navigation/images/img/coocolors.ico
    description: è®¾è®¡å¸ˆé…è‰²ç¥å™¨
  - name: ç¨¿å®šè®¾è®¡
    url: https://www.gaoding.com/
    img: /navigation/images/img/gaoding.png
    description: å…è´¹åœ¨çº¿PSï¼Œåœ¨çº¿æŠ å›¾ï¼Œåœ¨çº¿ç”Ÿæˆæµ·æŠ¥
  - name: World Vector Logo
    url: https://worldvectorlogo.com/
    img: /navigation/images/img/worldvectorlogo.png
    description: Brand logos free to download
  - name: LOGOåœ¨çº¿è®¾è®¡
    url: http://www.uugai.com/
    img: /navigation/images/img/yi.png
    description: å…è´¹çš„LOGOåœ¨çº¿è®¾è®¡åˆ¶ä½œå·¥å…·
  - name: Cool Background
    url: https://coolbackgrounds.io/
    img: /navigation/images/img/coolbackgrounds.png
    description: ç‚«é…·èƒŒæ™¯åœ¨çº¿ç”Ÿæˆå™¨
study:
  - name: èœé¸Ÿæ•™ç¨‹
    url: https://www.runoob.com/
    img: /navigation/images/img/runoob.png
    description: å­¦çš„ä¸ä»…æ˜¯æŠ€æœ¯ï¼Œæ›´æ˜¯æ¢¦æƒ³ï¼
  - name: W3school
    url: https://www.w3school.com.cn/
    img: /navigation/images/img/w3school.png
    description: é¢†å…ˆçš„webæŠ€æœ¯æ•™ç¨‹
  - name: ç‰›å®¢ç½‘
    url: https://www.nowcoder.com/
    img: /navigation/images/img/nowcoder.png
    description: ç‰›å®¢ç½‘ - äº’è”ç½‘æ±‚èŒç¥å™¨å’Œå¤‡è€ƒå­¦ä¹ å¹³å°
  - name: How2J
    url: https://how2j.cn/
    img: /navigation/images/img/how2j.png
    description: How2Jçš„Javaæ•™ç¨‹, å†…å®¹æ¶µç›–J2SEã€WEBå‰ç«¯ã€J2EEã€æ¡†æ¶æŠ€æœ¯ç­‰å…¨é¢çš„Javaå†…å®¹
qianduan:
  - name: Semantic-ui
    url: https://semantic-ui.com/
    img: /navigation/images/img/logo.png
    description: User Interface is the language of the web
  - name: Element
    url: https://element.eleme.cn/#/zh-CN
    img: /navigation/images/img/element.ico
    description: Elementï¼Œä¸€å¥—ä¸ºå¼€å‘è€…ã€è®¾è®¡å¸ˆå’Œäº§å“ç»ç†å‡†å¤‡çš„åŸºäº Vue 2.0 çš„æ¡Œé¢ç«¯ç»„ä»¶åº“
  - name: Bootstrap
    url: https://v3.bootcss.com/
    img: /navigation/images/img/bootstrap.ico
    description: Bootstrap æ˜¯æœ€å—æ¬¢è¿çš„ HTMLã€CSS å’Œ JS æ¡†æ¶ï¼Œç”¨äºå¼€å‘å“åº”å¼å¸ƒå±€ã€ç§»åŠ¨è®¾å¤‡ä¼˜å…ˆçš„ WEB é¡¹ç›®ã€‚
  - name: Vue.js
    url: https://cn.vuejs.org/
    img: /navigation/images/img/vue.png
    description: æ¸è¿›å¼JavaScript æ¡†æ¶
class:
  - name: jQuery
    url: https://jquery.com/
    img: /navigation/images/img/jquery.png
    description: jQuery
  - name: Echarts
    url: https://echarts.apache.org/zh/index.html
    img: /navigation/images/img/echarts.png
    description: å›¾è¡¨
  - name: jQueryæ’ä»¶åº“
    url: https://www.jq22.com/
    img: /navigation/images/img/jq22.ico
    description: jQueryæ’ä»¶åº“
website:
  - name: uni-app
    url: https://uniapp.dcloud.io/
    img: /navigation/images/img/uni-app.png
    description: å¼€å‘ä¸€æ¬¡ï¼Œå¤šç«¯è¦†ç›–
  - name: DCloud æ’ä»¶å¸‚åœº
    url: https://ext.dcloud.net.cn/
    img: /navigation/images/img/favicon.png
    description: DCloud æ’ä»¶å¸‚åœº
  - name: cron-job
    url: https://cron-job.org/en/
    img: /navigation/images/img/cron.ico
    description: å®šæ—¶ä»»åŠ¡ç½‘ç«™
  - name: I tell you(MSDN)
    url: https://next.itellyou.cn/
    img: https://cdn.jsdelivr.net/gh/jinan6/PicGo-img/img/20200622102946.png
    description: æä¾›å¯é çš„åŸç‰ˆè½¯ä»¶ï¼Œç”µè„‘ç³»ç»Ÿ
community:
  - name: CSDN
    url: https://www.csdn.net/
    img: /navigation/images/img/csdn.png
    description: å…¨çƒæœ€å¤§ä¸­æ–‡ITç¤¾åŒºï¼Œä¸ºITä¸“ä¸šæŠ€æœ¯äººå‘˜æä¾›æœ€å…¨é¢çš„ä¿¡æ¯ä¼ æ’­å’ŒæœåŠ¡å¹³å°
  - name: åšå®¢å›­
    url: https://www.cnblogs.com/
    img: /navigation/images/img/cnblogs.png
    description: ä»£ç æ”¹å˜ä¸–ç•Œ
  - name: æ˜é‡‘
    url: https://juejin.im/
    img: /navigation/images/img/juejin.png
    description: ä¸€ä¸ªå¸®åŠ©å¼€å‘è€…æˆé•¿çš„ç¤¾åŒº
  - name: ç®€ä¹¦
    url: https://www.jianshu.com/
    img: /navigation/images/img/jianshu.png
    description: åˆ›ä½œä½ çš„åˆ›ä½œ
  - name: å¼€æºä¸­å›½
    url: https://www.oschina.net/
    img: /navigation/images/img/oschina.png
    description: å›½å†…æœ€å¤§çš„å¼€æºæŠ€æœ¯ç¤¾åŒº
  - name: çŸ¥ä¹
    url: https://www.zhihu.com/
    img: /navigation/images/img/zhihu.png
    description: å›½å†…æœ€å—æ¬¢è¿çš„çŸ¥è¯†æ€§é—®ç­”ç¤¾åŒº
  - name: å¾çˆ±ç ´è§£
    url: https://www.52pojie.cn/
    img: /navigation/images/img/52pojie.png
    description: è‡´åŠ›äºè½¯ä»¶å®‰å…¨ä¸ç—…æ¯’åˆ†æçš„å‰æ²¿ï¼Œä¸°å¯Œçš„æŠ€æœ¯ç‰ˆå—äº¤ç›¸è¾‰æ˜ ï¼Œç”±æ— æ•°çƒ­è¡·äºè½¯ä»¶åŠ å¯†è§£å¯†åŠåç—…æ¯’çˆ±å¥½è€…å…±åŒç»´æŠ¤
  - name: WINOS
    url: https://www.winos.me/
    img: /navigation/images/img/winos.ico
    description: å‰æ²¿çš„ç²¾ç®€ç³»ç»Ÿä¸‹è½½
collocation:
  - name: Github
    url: https://github.com/
    img: /navigation/images/img/github.png
    description: å…¨çƒæœ€å¤§çš„é¢å‘å¼€æºåŠç§æœ‰è½¯ä»¶é¡¹ç›®çš„æ‰˜ç®¡å¹³å°
  - name: Gitlab
    url: https://gitlab.com/
    img: /navigation/images/img/gitlab.png
    description: æ”¯æŒæ— é™çš„å…¬æœ‰é¡¹ç›®å’Œç§æœ‰é¡¹ç›®çš„ä»£ç æ‰˜ç®¡å¹³å°
  - name: ç äº‘-Gitee
    url: https://gitee.com
    img: /navigation/images/img/gitee.ico
    description: ç äº‘(gitee.com)æ˜¯ OSCHINA.NET æ¨å‡ºçš„ä»£ç æ‰˜ç®¡å¹³å°ï¼Œæ”¯æŒ Git å’Œ SVNï¼Œæä¾›å…è´¹çš„ç§æœ‰ä»“åº“æ‰˜ç®¡ã€‚
  - name: CODING
    url: https://coding.net/
    img: /navigation/images/img/coding.ico
    description: Coding.net æ˜¯ä¸€ä¸ªé¢å‘å¼€å‘è€…çš„äº‘ç«¯å¼€å‘å¹³å°.
  - name: Vercel
    url: https://vercel.com/
    img: /navigation/images/img/vercel.png
    description: æ›¾ç»çš„zeitï¼Œé€Ÿåº¦è¿˜å¯ä»¥ã€‚
yun:
  - name: é˜¿é‡Œäº‘
    url: https://www.aliyun.com/
    img: /navigation/images/img/aliyun.png
    description: é˜¿é‡Œäº‘ - ä¸ºäº†æ— æ³•è®¡ç®—çš„ä»·å€¼
  - name: è…¾è®¯äº‘
    url: https://cloud.tencent.com/
    img: /navigation/images/img/cloudtencent.png
    description: è…¾è®¯äº‘ - äº§ä¸šæ™ºå˜ äº‘å¯æœªæ¥
  - name: åä¸ºäº‘
    url: https://www.huaweicloud.com/
    img: /navigation/images/img/huaweicloud.png
    description: åä¸ºäº‘ - +æ™ºèƒ½ï¼Œè§æœªæ¥
  - name: ä¸ƒç‰›äº‘
    url: https://www.qiniu.com/
    img: /navigation/images/img/qiniu.png
    description: ä¸ƒç‰›äº‘ - å›½å†…é¢†å…ˆçš„ä¼ä¸šçº§äº‘æœåŠ¡å•†
  - name: åˆæ‹äº‘
    url: https://www.upyun.com/
    img: /navigation/images/img/upyun.png
    description: åˆæ‹äº‘ - åŠ é€Ÿåœ¨çº¿ä¸šåŠ¡-CDN-äº‘å­˜å‚¨
  - name: Cloudflare
    url: https://www.cloudflare.com/
    img: /navigation/images/img/cloudflare.png
    description: Cloudflare - ç½‘ç»œæ€§èƒ½å’Œå®‰å…¨å…¬å¸
  - name: jsdelivr
    url: https://www.jsdelivr.com/
    img: /navigation/images/img/jsdelivr.png
    description: jsDelivr - A free, fast, and reliable Open Source CDN for npm and GitHub
me:
  - name: Sakura` Blogs
    url: https://jinan6.vip
    img: /navigation/images/img/author.jpg
    description: æ­å»ºåœ¨ Github
  - name: Sakura` Blogs
    url: https://only_ann.gitee.io/next/
    img: /navigation/images/img/author.jpg
    description: Nextä¸»é¢˜ï¼Œå·²åœæ­¢ç»´æŠ¤æ›´æ–°ã€‚
  - name: Sakura` Blogs
    url: https://only_ann.gitee.io/blog/
    img: /navigation/images/img/author.jpg
    description: æ­å»ºåœ¨ Gitee
  - name: ä»…å®‰ã®ä¸ªäººä¸»é¡µ
    url: https://blog.jinan6.vip/
    img: /navigation/images/img/author.jpg
    description: ä¸ªäººä¸»é¡µ
  - name: ä»…å®‰ã®ç½‘å€å¯¼èˆª
    url: https://only_ann.gitee.io/navigation/
    img: /navigation/images/img/author.jpg
    description: ç½‘å€å¯¼èˆª
  - name: ä»…å®‰ã®ç½‘ç«™ç›‘æ§
    url: https://jinan6.vip/status/
    img: /navigation/images/img/author.jpg
    description: ç½‘ç«™ç›‘æ§
about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

aboutPage:
  website:
    head: å…³äºæœ¬ç«™
    html: <p style="text-align:center;">ğŸ“¢ğŸ“¢ğŸ“¢æœ¬ç«™æ˜¯æˆ‘æ”¶é›†çš„ä¸€äº›å¸¸ç”¨çš„ç½‘å€ï¼Œä¸ºäº†æ–¹ä¾¿ä»¥åå¯»æ‰¾ï¼Œä¾¿æ•´ç†äº†æ­¤ç«™ã€‚<br>äº2020å¹´8æœˆ28æ—¥æ­å»ºå…¶é›å½¢ï¼Œä»¥åä¼šè¿›è¡Œè¡¥å……ã€‚<br>ä¸‹æ–¹æ˜¯æˆ‘çš„ä¸ªäººåšå®¢ï¼Œæ¬¢è¿æ¥è®¿</p>
  webmaster:
    head: å…³äºç«™é•¿
    name: ä»…å®‰
    url: https://jinan6.vip
    img: https://cdn.jsdelivr.net/gh/jinan6/PicGo-img/img/20200617192549.png
    description: æˆ–è‹¦æˆ–ç”œéƒ½ä¸è¦è¾œè´Ÿ

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°<head></head>æ ‡ç­¾å†…ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->
  body: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°</body>æ ‡ç­¾ä¹‹å‰ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
